In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Processo de Coleta de dados e Organização

### 1.Variáveis Macroeconômicas

- IPCA

In [15]:
df_ipca = pd.read_csv('../../data/Macroeconomicas/ipca_ibge.csv', index_col=0, parse_dates=True)

In [16]:
df_ipca.tail()

            ipca
data
26/11/2025  0.18
27/11/2025  0.18
28/11/2025  0.18
29/11/2025  0.18
30/11/2025  0.18

In [6]:
df_ipca.count()

data    2161
ipca    2161
dtype: int64

- SELIC

In [17]:
df_selic = pd.read_csv('../../data/Macroeconomicas/taxa_selic.csv', sep=',', index_col=0, parse_dates=True)

In [18]:
df_selic.tail()

            selic
data
24/12/2025   14.9
26/12/2025   14.9
29/12/2025   14.9
30/12/2025   14.9
31/12/2025   14.9

In [9]:
df_selic.count()

data     1507
selic    1507
dtype: int64

- PIB

In [19]:
df_pib = pd.read_csv('../../data/Macroeconomicas/pib_diario.csv', sep=',', index_col=0, parse_dates=True)

In [20]:
df_pib.tail()

            pib_brasil
data
27/12/2025         0.4
28/12/2025         0.4
29/12/2025         0.4
30/12/2025         0.4
31/12/2025         0.4

In [12]:
df_pib.count()

data          2192
pib_brasil    2192
dtype: int64

- Balança comercial do agronegócio

In [21]:
df_pib_agro = pd.read_csv('../../data/Macroeconomicas/pib_agro.csv', sep=',', index_col=0, parse_dates=True)

In [22]:
df_pib_agro.tail()

            pib_agro
data
27/12/2025      -2.5
28/12/2025      -2.5
29/12/2025      -2.5
30/12/2025      -2.5
31/12/2025      -2.5

In [13]:
df_pib_agro.count()

data        2192
pib_agro    2192
dtype: int64

- Chicago Mercantile Exchange (CME)

In [23]:
df_cme = pd.read_csv('../../data/Macroeconomicas/cme.csv', sep=',', index_col=0, parse_dates=True)

In [24]:
df_cme.tail()

               cme
data
24/12/2025  276.38
26/12/2025  276.73
29/12/2025  278.42
30/12/2025  275.83
31/12/2025  273.08

In [16]:
df_cme.count()

data    1508
cme     1508
dtype: int64

In [25]:
df_merge = pd.merge(df_selic, df_ipca, on='data', how='left')

In [26]:
df_merge.tail()

            selic  ipca
data
24/12/2025   14.9   NaN
26/12/2025   14.9   NaN
29/12/2025   14.9   NaN
30/12/2025   14.9   NaN
31/12/2025   14.9   NaN

In [27]:
df_merge = pd.merge(df_merge, df_pib, on='data', how='left')

In [28]:
df_merge.tail()

            selic  ipca  pib_brasil
data
24/12/2025   14.9   NaN         0.4
26/12/2025   14.9   NaN         0.4
29/12/2025   14.9   NaN         0.4
30/12/2025   14.9   NaN         0.4
31/12/2025   14.9   NaN         0.4

In [29]:
df_merge.count()

selic         1507
ipca          1485
pib_brasil    1507
dtype: int64

In [30]:
df_merge = pd.merge(df_merge, df_pib_agro, on='data', how='left')

In [31]:
df_merge.tail()

            selic  ipca  pib_brasil  pib_agro
data
24/12/2025   14.9   NaN         0.4      -2.5
26/12/2025   14.9   NaN         0.4      -2.5
29/12/2025   14.9   NaN         0.4      -2.5
30/12/2025   14.9   NaN         0.4      -2.5
31/12/2025   14.9   NaN         0.4      -2.5

### Gerando o dataframe final para as variáveis Macroeconômicas

In [32]:
df_macro = pd.merge(df_merge, df_cme, on='data', how='left')

In [33]:
df_macro.tail()

            selic  ipca  pib_brasil  pib_agro     cme
data
24/12/2025   14.9   NaN         0.4      -2.5  276.38
26/12/2025   14.9   NaN         0.4      -2.5  276.73
29/12/2025   14.9   NaN         0.4      -2.5  278.42
30/12/2025   14.9   NaN         0.4      -2.5  275.83
31/12/2025   14.9   NaN         0.4      -2.5  273.08

In [34]:
df_macro.shape

(1507, 5)

In [35]:
df_macro.isna().sum().sum()

np.int64(62)

## 2. Variáveis de Mercado

- Preço Boi Gordo

In [36]:
df_boi_gordo_negociado = pd.read_csv('../../data/Mercado/boi_gordo_negociado.csv', sep=',', index_col=0, parse_dates=True)

In [37]:
df_boi_gordo_negociado.tail()

            boi_real  boi_dolar
data
22/12/2025    317.85      56.94
23/12/2025    319.50      57.69
26/12/2025    319.50      57.69
29/12/2025    318.00      57.00
30/12/2025    319.20      58.16

In [38]:
df_boi_gordo_negociado.count()

boi_real     1496
boi_dolar    1496
dtype: int64

- Contrato Boi Gordo Futuro

In [39]:
df_boi_gordo_futuro = pd.read_csv('../../data/Mercado/boi_gordo_futuro.csv', sep=',', index_col=0, parse_dates=True)

In [40]:
df_boi_gordo_futuro.tail()

            boi_futuro
data
24/12/2025      228.70
26/12/2025      229.82
29/12/2025      228.90
30/12/2025      231.18
31/12/2025      232.00

In [41]:
df_boi_gordo_futuro.count()

boi_futuro    1514
dtype: int64

In [42]:
df_merge_mercado = pd.merge(df_boi_gordo_futuro, df_boi_gordo_negociado, on='data', how='left')

In [43]:
df_merge_mercado.tail()

            boi_futuro  boi_real  boi_dolar
data
24/12/2025      228.70       NaN        NaN
26/12/2025      229.82     319.5      57.69
29/12/2025      228.90     318.0      57.00
30/12/2025      231.18     319.2      58.16
31/12/2025      232.00       NaN        NaN

In [44]:
df_merge_mercado.count()

boi_futuro    1514
boi_real      1459
boi_dolar     1459
dtype: int64

- Soja

In [45]:
df_soja_negociado = pd.read_csv('../../data/Mercado/soja_negociado.csv', sep=',', index_col=0, parse_dates=True)

In [46]:
df_soja_negociado.tail()

            soja_real  soja_dolar
data
22/12/2025     136.16       24.39
23/12/2025     136.20       24.59
26/12/2025     136.23       24.57
29/12/2025     136.21       24.41
30/12/2025     135.60       24.71

- Contrato Soja Futuro

In [47]:
df_soja_negociado.count()

soja_real     1497
soja_dolar    1497
dtype: int64

In [48]:
df_merge_mercado = pd.merge(df_merge_mercado, df_soja_negociado, on='data', how='left')

In [49]:
df_merge_mercado.tail()

            boi_futuro  boi_real  boi_dolar  soja_real  soja_dolar
data
24/12/2025      228.70       NaN        NaN        NaN         NaN
26/12/2025      229.82     319.5      57.69     136.23       24.57
29/12/2025      228.90     318.0      57.00     136.21       24.41
30/12/2025      231.18     319.2      58.16     135.60       24.71
31/12/2025      232.00       NaN        NaN        NaN         NaN

In [50]:
df_soja_futuro = pd.read_csv('../../data/Mercado/soja_futuro.csv', sep=',', index_col=0, parse_dates=True)

In [51]:
df_soja_futuro.tail()

            soja_futuro
data
22/12/2025     232198.0
23/12/2025     231812.0
26/12/2025     233410.0
29/12/2025     231371.0
30/12/2025     234182.0

In [52]:
df_soja_futuro.count()

soja_futuro    1538
dtype: int64

In [53]:
df_merge_mercado = pd.merge(df_merge_mercado, df_soja_futuro, on='data', how='left')

In [54]:
df_merge_mercado.tail()

,boi_futuro,boi_real,boi_dolar,soja_real,soja_dolar,soja_futuro
data,,,,,,
24/12/2025,228.70,NaN,NaN,NaN,NaN,NaN
26/12/2025,229.82,319.5,57.69,136.23,24.57,233410.0
29/12/2025,228.90,318.0,57.00,136.21,24.41,231371.0
30/12/2025,231.18,319.2,58.16,135.60,24.71,234182.0
31/12/2025,232.00,NaN,NaN,NaN,NaN,NaN

In [55]:
df_merge_mercado.count()

boi_futuro     1514
boi_real       1459
boi_dolar      1459
soja_real      1460
soja_dolar     1460
soja_futuro    1510
dtype: int64

- Milho

In [56]:
df_milho_futuro = pd.read_csv('../../data/Mercado/milho_futuro.csv', sep=',', index_col=0, parse_dates=True)

In [57]:
df_milho_futuro.tail()

            milho_futuro
data
22/12/2025         70.99
23/12/2025         70.81
26/12/2025         70.08
29/12/2025         70.28
30/12/2025         70.25

In [58]:
df_milho_futuro.count()

milho_futuro    1494
dtype: int64

In [59]:
df_merge_mercado = pd.merge(df_merge_mercado, df_milho_futuro, on='data', how='left')

In [60]:
df_merge_mercado.tail()

,boi_futuro,boi_real,boi_dolar,soja_real,soja_dolar,soja_futuro,milho_futuro
data,,,,,,,
24/12/2025,228.70,NaN,NaN,NaN,NaN,NaN,NaN
26/12/2025,229.82,319.5,57.69,136.23,24.57,233410.0,70.08
29/12/2025,228.90,318.0,57.00,136.21,24.41,231371.0,70.28
30/12/2025,231.18,319.2,58.16,135.60,24.71,234182.0,70.25
31/12/2025,232.00,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
df_milho_negociado = pd.read_csv('../../data/Mercado/milho_negociado.csv', sep=',', index_col=0, parse_dates=True)

In [62]:
df_milho_negociado.tail()

            milho_real  milho_dolar
data
22/12/2025       69.47        12.45
23/12/2025       69.50        12.55
26/12/2025       69.48        12.53
29/12/2025       69.46        12.45
30/12/2025       69.50        12.66

In [63]:
df_milho_negociado.count()

milho_real     1497
milho_dolar    1497
dtype: int64

In [64]:
df_merge_mercado = pd.merge(df_merge_mercado, df_milho_negociado, on='data', how='left')

In [65]:
df_merge_mercado.tail()

,boi_futuro,boi_real,boi_dolar,soja_real,soja_dolar,soja_futuro,milho_futuro,milho_real,milho_dolar
data,,,,,,,,,
24/12/2025,228.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26/12/2025,229.82,319.5,57.69,136.23,24.57,233410.0,70.08,69.48,12.53
29/12/2025,228.90,318.0,57.00,136.21,24.41,231371.0,70.28,69.46,12.45
30/12/2025,231.18,319.2,58.16,135.60,24.71,234182.0,70.25,69.50,12.66
31/12/2025,232.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
df_merge_mercado.count()

boi_futuro      1514
boi_real        1459
boi_dolar       1459
soja_real       1460
soja_dolar      1460
soja_futuro     1510
milho_futuro    1457
milho_real      1460
milho_dolar     1460
dtype: int64

In [67]:
df_dolar = pd.read_csv('../../data/Mercado/dolar.csv', sep=',', index_col=0, parse_dates=True)

In [68]:
df_dolar.tail()

            dolar
data
22/12/2025  5.582
23/12/2025  5.538
26/12/2025  5.544
29/12/2025  5.579
30/12/2025  5.488

In [69]:
df_dolar.count()

dolar    1562
dtype: int64

In [70]:
df_merge_mercado = pd.merge(df_merge_mercado, df_dolar, on='data', how='left')

In [71]:
df_merge_mercado.tail()

,boi_futuro,boi_real,boi_dolar,soja_real,soja_dolar,soja_futuro,milho_futuro,milho_real,milho_dolar,dolar
data,,,,,,,,,,
24/12/2025,228.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26/12/2025,229.82,319.5,57.69,136.23,24.57,233410.0,70.08,69.48,12.53,5.544
29/12/2025,228.90,318.0,57.00,136.21,24.41,231371.0,70.28,69.46,12.45,5.579
30/12/2025,231.18,319.2,58.16,135.60,24.71,234182.0,70.25,69.50,12.66,5.488
31/12/2025,232.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
df_tarifa_china = pd.read_csv('../../data/Mercado/tarifa_China.csv', sep=',', index_col=0, parse_dates=True)

In [73]:
df_tarifa_china.tail()

            Taxa_china
data
27/12/2025        0.12
28/12/2025        0.12
29/12/2025        0.12
30/12/2025        0.12
31/12/2025        0.12

In [74]:
df_mercado = pd.merge(df_tarifa_china, df_merge_mercado, on='data', how='left')

In [75]:
df_tarifa_UE = pd.read_csv('../../data/Mercado/tarifa_UE.csv', sep=',', index_col=0, parse_dates=True)

In [76]:
df_tarifa_UE.tail()

            Taxa_EU
data
27/12/2025     0.42
28/12/2025     0.42
29/12/2025     0.42
30/12/2025     0.42
31/12/2025     0.42

In [77]:
df_mercado = pd.merge(df_tarifa_UE, df_mercado, on='data', how='left')

In [78]:
df_tarifa_EUA = pd.read_csv('../../data/Mercado/tarifa_EUA.csv', sep=',', index_col=0, parse_dates=True)

In [79]:
df_tarifa_EUA.tail()

            Taxa_EUA
data
27/12/2025      0.26
28/12/2025      0.26
29/12/2025      0.26
30/12/2025      0.26
31/12/2025      0.26

### Gerando o dataframe final para as variáveis de mercado

In [80]:
df_mercado = pd.merge(df_tarifa_EUA, df_mercado, on='data', how='left')

In [81]:
df_mercado.tail()

,Taxa_EUA,Taxa_EU,Taxa_china,boi_futuro,boi_real,boi_dolar,soja_real,soja_dolar,soja_futuro,milho_futuro,milho_real,milho_dolar,dolar
data,,,,,,,,,,,,,
27/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29/12/2025,0.26,0.42,0.12,228.90,318.0,57.00,136.21,24.41,231371.0,70.28,69.46,12.45,5.579
30/12/2025,0.26,0.42,0.12,231.18,319.2,58.16,135.60,24.71,234182.0,70.25,69.50,12.66,5.488
31/12/2025,0.26,0.42,0.12,232.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [82]:
df_mercado.shape

(2192, 13)

In [83]:
df_mercado.isna().sum().sum()

np.int64(7170)

## 3. Variáveis Climáticas

- Precipitação por região produtora

In [84]:
df_precip_area = pd.read_csv('../../data/Climaticas/INMET.csv', sep=',', index_col=0, parse_dates=True)

In [85]:
df_precip_area.tail()

            precip_total_mm
data
27/12/2025              0.0
28/12/2025              0.0
29/12/2025              0.0
30/12/2025              0.0
31/12/2025             10.8

In [86]:
df_precip_area.count()

precip_total_mm    1971
dtype: int64

- Temperatura Média

In [87]:
df_temp_regiao = pd.read_csv('../../data/Climaticas/temp.csv', index_col=0, parse_dates=True)

In [88]:
df_temp_regiao.tail()

            TEMPERATURA
data
27/12/2025        29.90
28/12/2025        30.06
29/12/2025        28.14
30/12/2025        27.66
31/12/2025        26.90

In [89]:
df_temp_regiao.count()

TEMPERATURA    2158
dtype: int64

- Índices de seca (Palmer Drought Severity Index)

Valor do PDSI	Interpretação
≥ +4,0	        Muito úmido
+3,0 a +3,9	    Moderadamente úmido
+2,0 a +2,9	    Levemente úmido
+1,0 a +1,9	    Condições normais (úmidas)
0,0 a +0,9	    Normal
-0,9 a 0,0	    Normal
-1,0 a -1,9	    Levemente seco
-2,0 a -2,9	    Moderadamente seco
-3,0 a -3,9	    Severamente seco
≤ -4,0	        Extremamente seco

In [90]:
df_scpdsi = pd.read_csv('../../data/Climaticas/scpdsi.csv', index_col=0, parse_dates=True)

In [91]:
df_scpdsi.count()

scpdsi    2192
dtype: int64

In [92]:
df_scpdsi.tail()

            scpdsi
data
27/12/2025    -0.0
28/12/2025    -0.0
29/12/2025    -0.0
30/12/2025    -0.0
31/12/2025    -0.0

- El niño

In [93]:
df_el_nino = pd.read_csv('../../data/Climaticas/el_nino.csv', index_col=0, parse_dates=True)

In [94]:
df_el_nino.count()

el nino    2209
dtype: int64

In [95]:
df_el_nino.tail()

                el nino
data
27/12/2025  INEXISTENTE
28/12/2025  INEXISTENTE
29/12/2025  INEXISTENTE
30/12/2025  INEXISTENTE
31/12/2025  INEXISTENTE

In [96]:
df_climaticas = pd.merge(df_scpdsi, df_el_nino, on='data', how='left')

In [97]:
df_climaticas.tail()

            scpdsi      el nino
data
27/12/2025    -0.0  INEXISTENTE
28/12/2025    -0.0  INEXISTENTE
29/12/2025    -0.0  INEXISTENTE
30/12/2025    -0.0  INEXISTENTE
31/12/2025    -0.0  INEXISTENTE

In [98]:
df_climaticas.count()

scpdsi     2209
el nino    2209
dtype: int64

In [99]:
df_climaticas = pd.merge(df_climaticas, df_precip_area, on='data', how='left')

In [100]:
df_climaticas = pd.merge(df_climaticas, df_temp_regiao, on='data', how='left')

In [101]:
df_climaticas.tail()

            scpdsi      el nino  precip_total_mm  TEMPERATURA
data
27/12/2025    -0.0  INEXISTENTE              0.0        29.90
28/12/2025    -0.0  INEXISTENTE              0.0        30.06
29/12/2025    -0.0  INEXISTENTE              0.0        28.14
30/12/2025    -0.0  INEXISTENTE              0.0        27.66
31/12/2025    -0.0  INEXISTENTE             10.8        26.90

In [102]:
df_climaticas.count()

scpdsi             2209
el nino            2209
precip_total_mm    1988
TEMPERATURA        2175
dtype: int64

## 4. Variáveis Sazonais

- Ciclo Reprodutivo do gado

In [105]:
df_ciclo_rep_gado = pd.read_csv('../../data/Sazonais/rep_gado.csv', index_col=0, parse_dates=True)

In [106]:
df_ciclo_rep_gado.tail()

                    ciclo
data
27/12/2025  ESTACAO_MONTA
28/12/2025  ESTACAO_MONTA
29/12/2025  ESTACAO_MONTA
30/12/2025  ESTACAO_MONTA
31/12/2025  ESTACAO_MONTA

In [107]:
df_ciclo_rep_gado.count()

ciclo    2192
dtype: int64

- Safra e Entresafra

In [108]:
df_safra_entresafra = pd.read_csv('../../data/Sazonais/safra_entresafra.csv', index_col=0, parse_dates=True)

In [109]:
df_safra_entresafra.tail()

                 aspecto
data
27/12/2025  PLANEJAMENTO
28/12/2025  PLANEJAMENTO
29/12/2025  PLANEJAMENTO
30/12/2025  PLANEJAMENTO
31/12/2025  PLANEJAMENTO

In [110]:
df_safra_entresafra.count()

aspecto    2192
dtype: int64

- Festas e datas comemorativas

In [112]:
df_festas = pd.read_csv('../../data/Sazonais/festas_2020_2025.csv', index_col=0, parse_dates=True)

In [113]:
df_festas.tail()

,ano_novo_flag,carnaval_core_flag,carnaval_window_flag,pascoa_flag,pascoa_window_flag,dias_maes_flag,dias_maes_weekend_flag,festas_juninas_flag,santo_antonio_flag,sao_joao_flag,...,dias_pais_weekend_flag,independencia_flag,independencia_window_flag,dia_criancas_flag,finados_flag,finados_weekend_flag,natal_flag,natal_window_flag,fim_ano_window_flag,sazonal_carne_weight
data,,,,,,,,,,,,,,,,,,,,,
27/12/2025,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
28/12/2025,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
29/12/2025,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
30/12/2025,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1.5
31/12/2025,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1.5

In [114]:
df_festas.count()

ano_novo_flag                2192
carnaval_core_flag           2192
carnaval_window_flag         2192
pascoa_flag                  2192
pascoa_window_flag           2192
dias_maes_flag               2192
dias_maes_weekend_flag       2192
festas_juninas_flag          2192
santo_antonio_flag           2192
sao_joao_flag                2192
sao_pedro_flag               2192
ferias_midyear_flag          2192
ferias_verao_flag            2192
dias_pais_flag               2192
dias_pais_weekend_flag       2192
independencia_flag           2192
independencia_window_flag    2192
dia_criancas_flag            2192
finados_flag                 2192
finados_weekend_flag         2192
natal_flag                   2192
natal_window_flag            2192
fim_ano_window_flag          2192
sazonal_carne_weight         2192
dtype: int64

In [115]:
df_sazonais = pd.merge(df_ciclo_rep_gado, df_safra_entresafra, on='data', how='left')

In [116]:
df_sazonais.tail()

                    ciclo       aspecto
data
27/12/2025  ESTACAO_MONTA  PLANEJAMENTO
28/12/2025  ESTACAO_MONTA  PLANEJAMENTO
29/12/2025  ESTACAO_MONTA  PLANEJAMENTO
30/12/2025  ESTACAO_MONTA  PLANEJAMENTO
31/12/2025  ESTACAO_MONTA  PLANEJAMENTO

In [117]:
df_sazonais = pd.merge(df_sazonais, df_festas, on='data', how='left')

In [118]:
df_sazonais.tail()

,ciclo,aspecto,ano_novo_flag,carnaval_core_flag,carnaval_window_flag,pascoa_flag,pascoa_window_flag,dias_maes_flag,dias_maes_weekend_flag,festas_juninas_flag,...,dias_pais_weekend_flag,independencia_flag,independencia_window_flag,dia_criancas_flag,finados_flag,finados_weekend_flag,natal_flag,natal_window_flag,fim_ano_window_flag,sazonal_carne_weight
data,,,,,,,,,,,,,,,,,,,,,
27/12/2025,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
28/12/2025,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
29/12/2025,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
30/12/2025,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1.5
31/12/2025,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1.5

In [119]:
df_sazonais.count()

ciclo                        2192
aspecto                      2192
ano_novo_flag                2192
carnaval_core_flag           2192
carnaval_window_flag         2192
pascoa_flag                  2192
pascoa_window_flag           2192
dias_maes_flag               2192
dias_maes_weekend_flag       2192
festas_juninas_flag          2192
santo_antonio_flag           2192
sao_joao_flag                2192
sao_pedro_flag               2192
ferias_midyear_flag          2192
ferias_verao_flag            2192
dias_pais_flag               2192
dias_pais_weekend_flag       2192
independencia_flag           2192
independencia_window_flag    2192
dia_criancas_flag            2192
finados_flag                 2192
finados_weekend_flag         2192
natal_flag                   2192
natal_window_flag            2192
fim_ano_window_flag          2192
sazonal_carne_weight         2192
dtype: int64

## 5. Variáveis Exógenas

- COVID-19

In [120]:
df_covid = pd.read_csv('../../data/Exogenas/covid_2020_2025.csv', index_col=0, parse_dates=True)

In [121]:
df_covid.tail()

            CovidPeriodFlag
data
27/12/2025                0
28/12/2025                0
29/12/2025                0
30/12/2025                0
31/12/2025                0

In [123]:
df_covid.count()

CovidPeriodFlag    2192
dtype: int64

## Criando o dataframe Final

In [122]:
max(df_mercado.count())

2192

In [124]:
df_mercado.tail()

,Taxa_EUA,Taxa_EU,Taxa_china,boi_futuro,boi_real,boi_dolar,soja_real,soja_dolar,soja_futuro,milho_futuro,milho_real,milho_dolar,dolar
data,,,,,,,,,,,,,
27/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29/12/2025,0.26,0.42,0.12,228.90,318.0,57.00,136.21,24.41,231371.0,70.28,69.46,12.45,5.579
30/12/2025,0.26,0.42,0.12,231.18,319.2,58.16,135.60,24.71,234182.0,70.25,69.50,12.66,5.488
31/12/2025,0.26,0.42,0.12,232.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [125]:
max(df_macro.count())

1507

In [126]:
df_macro.tail()

            selic  ipca  pib_brasil  pib_agro     cme
data
24/12/2025   14.9   NaN         0.4      -2.5  276.38
26/12/2025   14.9   NaN         0.4      -2.5  276.73
29/12/2025   14.9   NaN         0.4      -2.5  278.42
30/12/2025   14.9   NaN         0.4      -2.5  275.83
31/12/2025   14.9   NaN         0.4      -2.5  273.08

In [127]:
max(df_climaticas.count())

2209

In [128]:
df_climaticas.tail()

            scpdsi      el nino  precip_total_mm  TEMPERATURA
data
27/12/2025    -0.0  INEXISTENTE              0.0        29.90
28/12/2025    -0.0  INEXISTENTE              0.0        30.06
29/12/2025    -0.0  INEXISTENTE              0.0        28.14
30/12/2025    -0.0  INEXISTENTE              0.0        27.66
31/12/2025    -0.0  INEXISTENTE             10.8        26.90

In [129]:
max(df_sazonais.count())

2192

In [130]:
df_sazonais.tail()

,ciclo,aspecto,ano_novo_flag,carnaval_core_flag,carnaval_window_flag,pascoa_flag,pascoa_window_flag,dias_maes_flag,dias_maes_weekend_flag,festas_juninas_flag,...,dias_pais_weekend_flag,independencia_flag,independencia_window_flag,dia_criancas_flag,finados_flag,finados_weekend_flag,natal_flag,natal_window_flag,fim_ano_window_flag,sazonal_carne_weight
data,,,,,,,,,,,,,,,,,,,,,
27/12/2025,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
28/12/2025,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
29/12/2025,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
30/12/2025,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1.5
31/12/2025,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1.5

In [131]:
max(df_covid.count())

2192

In [132]:
df_covid.tail()

            CovidPeriodFlag
data
27/12/2025                0
28/12/2025                0
29/12/2025                0
30/12/2025                0
31/12/2025                0

In [133]:
df_final = pd.merge(df_covid, df_sazonais, on='data', how='left')

In [134]:
df_final.tail()

,CovidPeriodFlag,ciclo,aspecto,ano_novo_flag,carnaval_core_flag,carnaval_window_flag,pascoa_flag,pascoa_window_flag,dias_maes_flag,dias_maes_weekend_flag,...,dias_pais_weekend_flag,independencia_flag,independencia_window_flag,dia_criancas_flag,finados_flag,finados_weekend_flag,natal_flag,natal_window_flag,fim_ano_window_flag,sazonal_carne_weight
data,,,,,,,,,,,,,,,,,,,,,
27/12/2025,0,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
28/12/2025,0,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
29/12/2025,0,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
30/12/2025,0,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1.5
31/12/2025,0,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1.5

In [135]:
df_final = pd.merge(df_final, df_climaticas, on='data', how='left')

In [136]:
df_final = pd.merge(df_final, df_macro, on='data', how='left')

In [137]:
df_agro_boi = pd.merge(df_mercado, df_final, on='data', how='left')

In [138]:
df_agro_boi.tail()

,Taxa_EUA,Taxa_EU,Taxa_china,boi_futuro,boi_real,boi_dolar,soja_real,soja_dolar,soja_futuro,milho_futuro,...,sazonal_carne_weight,scpdsi,el nino,precip_total_mm,TEMPERATURA,selic,ipca,pib_brasil,pib_agro,cme
data,,,,,,,,,,,,,,,,,,,,,
27/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.0,INEXISTENTE,0.0,29.90,NaN,NaN,NaN,NaN,NaN
28/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.0,INEXISTENTE,0.0,30.06,NaN,NaN,NaN,NaN,NaN
29/12/2025,0.26,0.42,0.12,228.90,318.0,57.00,136.21,24.41,231371.0,70.28,...,0.0,-0.0,INEXISTENTE,0.0,28.14,14.9,NaN,0.4,-2.5,278.42
30/12/2025,0.26,0.42,0.12,231.18,319.2,58.16,135.60,24.71,234182.0,70.25,...,1.5,-0.0,INEXISTENTE,0.0,27.66,14.9,NaN,0.4,-2.5,275.83
31/12/2025,0.26,0.42,0.12,232.00,NaN,NaN,NaN,NaN,NaN,NaN,...,1.5,-0.0,INEXISTENTE,10.8,26.90,14.9,NaN,0.4,-2.5,273.08

In [139]:
df_agro_boi.shape

(2209, 49)

In [140]:
s = df_agro_boi.shape[0]  * df_agro_boi.shape[1]

In [141]:
s

108241

In [142]:
df_agro_boi.dtypes

Taxa_EUA                     float64
Taxa_EU                      float64
Taxa_china                   float64
boi_futuro                   float64
boi_real                     float64
boi_dolar                    float64
soja_real                    float64
soja_dolar                   float64
soja_futuro                  float64
milho_futuro                 float64
milho_real                   float64
milho_dolar                  float64
dolar                        float64
CovidPeriodFlag                int64
ciclo                         object
aspecto                       object
ano_novo_flag                  int64
carnaval_core_flag             int64
carnaval_window_flag           int64
pascoa_flag                    int64
pascoa_window_flag             int64
dias_maes_flag                 int64
dias_maes_weekend_flag         int64
festas_juninas_flag            int64
santo_antonio_flag             int64
sao_joao_flag                  int64
sao_pedro_flag                 int64
ferias_midyear_flag            int64
ferias_verao_flag              int64
dias_pais_flag                 int64
dias_pais_weekend_flag         int64
independencia_flag             int64
independencia_window_flag      int64
dia_criancas_flag              int64
finados_flag                   int64
finados_weekend_flag           int64
natal_flag                     int64
natal_window_flag              int64
fim_ano_window_flag            int64
sazonal_carne_weight         float64
scpdsi                       float64
el nino                       object
precip_total_mm              float64
TEMPERATURA                  float64
selic                        float64
ipca                         float64
pib_brasil                   float64
pib_agro                     float64
cme                          float64
dtype: object

In [143]:
df_agro_boi.drop(columns=[])

,Taxa_EUA,Taxa_EU,Taxa_china,boi_futuro,boi_real,boi_dolar,soja_real,soja_dolar,soja_futuro,milho_futuro,...,sazonal_carne_weight,scpdsi,el nino,precip_total_mm,TEMPERATURA,selic,ipca,pib_brasil,pib_agro,cme
data,,,,,,,,,,,,,,,,,,,,,
01/01/2020,0.26,0.42,0.12,125.97,NaN,NaN,NaN,NaN,943.50,NaN,...,1.5,0.44,INEXISTENTE,0.0,30.67,NaN,NaN,NaN,NaN,NaN
02/01/2020,0.26,0.42,0.12,125.78,192.95,47.96,82.92,20.61,956.25,49.11,...,0.5,0.44,INEXISTENTE,0.0,28.33,4.4,0.21,-0.7,2.0,201.85
03/01/2020,0.26,0.42,0.12,124.72,196.70,48.53,83.01,20.48,941.50,48.92,...,0.5,0.44,INEXISTENTE,0.2,26.00,4.4,0.21,-0.7,2.0,204.55
04/01/2020,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.5,0.44,INEXISTENTE,0.8,25.95,NaN,NaN,NaN,NaN,NaN
05/01/2020,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.5,0.44,INEXISTENTE,0.0,28.10,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.00,INEXISTENTE,0.0,29.90,NaN,NaN,NaN,NaN,NaN
28/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.00,INEXISTENTE,0.0,30.06,NaN,NaN,NaN,NaN,NaN
29/12/2025,0.26,0.42,0.12,228.90,318.00,57.00,136.21,24.41,231371.00,70.28,...,0.0,-0.00,INEXISTENTE,0.0,28.14,14.9,NaN,0.4,-2.5,278.42
30/12/2025,0.26,0.42,0.12,231.18,319.20,58.16,135.60,24.71,234182.00,70.25,...,1.5,-0.00,INEXISTENTE,0.0,27.66,14.9,NaN,0.4,-2.5,275.83
31/12/2025,0.26,0.42,0.12,232.00,NaN,NaN,NaN,NaN,NaN,NaN,...,1.5,-0.00,INEXISTENTE,10.8,26.90,14.9,NaN,0.4,-2.5,273.08

In [146]:
df_agro_boi.to_csv("dados_agro.csv", index=True)

In [147]:
df = pd.read_csv("dados_agro.csv", index_col=0, parse_dates=True)
df.tail()

,Taxa_EUA,Taxa_EU,Taxa_china,boi_futuro,boi_real,boi_dolar,soja_real,soja_dolar,soja_futuro,milho_futuro,...,sazonal_carne_weight,scpdsi,el nino,precip_total_mm,TEMPERATURA,selic,ipca,pib_brasil,pib_agro,cme
data,,,,,,,,,,,,,,,,,,,,,
27/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.0,INEXISTENTE,0.0,29.90,NaN,NaN,NaN,NaN,NaN
28/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.0,INEXISTENTE,0.0,30.06,NaN,NaN,NaN,NaN,NaN
29/12/2025,0.26,0.42,0.12,228.90,318.0,57.00,136.21,24.41,231371.0,70.28,...,0.0,-0.0,INEXISTENTE,0.0,28.14,14.9,NaN,0.4,-2.5,278.42
30/12/2025,0.26,0.42,0.12,231.18,319.2,58.16,135.60,24.71,234182.0,70.25,...,1.5,-0.0,INEXISTENTE,0.0,27.66,14.9,NaN,0.4,-2.5,275.83
31/12/2025,0.26,0.42,0.12,232.00,NaN,NaN,NaN,NaN,NaN,NaN,...,1.5,-0.0,INEXISTENTE,10.8,26.90,14.9,NaN,0.4,-2.5,273.08

In [148]:
df.rename(columns={"boi_real":"boi_negociado"}, inplace=True)
df.tail()

,Taxa_EUA,Taxa_EU,Taxa_china,boi_futuro,boi_negociado,boi_dolar,soja_real,soja_dolar,soja_futuro,milho_futuro,...,sazonal_carne_weight,scpdsi,el nino,precip_total_mm,TEMPERATURA,selic,ipca,pib_brasil,pib_agro,cme
data,,,,,,,,,,,,,,,,,,,,,
27/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.0,INEXISTENTE,0.0,29.90,NaN,NaN,NaN,NaN,NaN
28/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.0,INEXISTENTE,0.0,30.06,NaN,NaN,NaN,NaN,NaN
29/12/2025,0.26,0.42,0.12,228.90,318.0,57.00,136.21,24.41,231371.0,70.28,...,0.0,-0.0,INEXISTENTE,0.0,28.14,14.9,NaN,0.4,-2.5,278.42
30/12/2025,0.26,0.42,0.12,231.18,319.2,58.16,135.60,24.71,234182.0,70.25,...,1.5,-0.0,INEXISTENTE,0.0,27.66,14.9,NaN,0.4,-2.5,275.83
31/12/2025,0.26,0.42,0.12,232.00,NaN,NaN,NaN,NaN,NaN,NaN,...,1.5,-0.0,INEXISTENTE,10.8,26.90,14.9,NaN,0.4,-2.5,273.08

In [150]:
df.to_csv("dados_agro_atualizado.csv", index=True)

In [151]:
new_df = pd.read_csv("dados_agro_atualizado.csv", index_col=0, parse_dates=True)

In [152]:
new_df[["ciclo","aspecto", "el nino"]].tail()

                    ciclo       aspecto      el nino
data
27/12/2025  ESTACAO_MONTA  PLANEJAMENTO  INEXISTENTE
28/12/2025  ESTACAO_MONTA  PLANEJAMENTO  INEXISTENTE
29/12/2025  ESTACAO_MONTA  PLANEJAMENTO  INEXISTENTE
30/12/2025  ESTACAO_MONTA  PLANEJAMENTO  INEXISTENTE
31/12/2025  ESTACAO_MONTA  PLANEJAMENTO  INEXISTENTE