In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Processo de Coleta de dados e Organização

### 1.Variáveis Macroeconômicas

- IPCA

In [2]:
df_ipca = pd.read_csv('Macroeconomicas/ipca_ibge.csv')

In [3]:
df_ipca.tail()

            data  ipca
2156  26/11/2025  0.18
2157  27/11/2025  0.18
2158  28/11/2025  0.18
2159  29/11/2025  0.18
2160  30/11/2025  0.18

In [4]:
df_ipca.count()

data    2161
ipca    2161
dtype: int64

- SELIC

In [5]:
df_selic = pd.read_csv('Macroeconomicas/taxa_selic.csv', sep=',')

In [6]:
df_selic.tail()

            data  selic
1502  24/12/2025   14.9
1503  26/12/2025   14.9
1504  29/12/2025   14.9
1505  30/12/2025   14.9
1506  31/12/2025   14.9

In [7]:
df_selic.count()

data     1507
selic    1507
dtype: int64

- PIB

In [8]:
df_pib = pd.read_csv('Macroeconomicas/pib_diario.csv', sep=',')

In [9]:
df_pib.tail()

            data  pib_brasil
2187  27/12/2025         0.4
2188  28/12/2025         0.4
2189  29/12/2025         0.4
2190  30/12/2025         0.4
2191  31/12/2025         0.4

In [10]:
df_pib.count()

data          2192
pib_brasil    2192
dtype: int64

- Balança comercial do agronegócio

In [11]:
df_pib_agro = pd.read_csv('Macroeconomicas/pib_agro.csv', sep=',')

In [12]:
df_pib_agro.tail()

            data  pib_agro
2187  27/12/2025      -2.5
2188  28/12/2025      -2.5
2189  29/12/2025      -2.5
2190  30/12/2025      -2.5
2191  31/12/2025      -2.5

In [13]:
df_pib_agro.count()

data        2192
pib_agro    2192
dtype: int64

- Chicago Mercantile Exchange (CME)

In [14]:
df_cme = pd.read_csv('Macroeconomicas/cme.csv', sep=',')

In [15]:
df_cme.tail()

            data     cme
1503  24/12/2025  276.38
1504  26/12/2025  276.73
1505  29/12/2025  278.42
1506  30/12/2025  275.83
1507  31/12/2025  273.08

In [16]:
df_cme.count()

data    1508
cme     1508
dtype: int64

In [17]:
df_merge = pd.merge(df_selic, df_ipca, on='data', how='left')

In [18]:
df_merge.tail()

            data  selic  ipca
1502  24/12/2025   14.9   NaN
1503  26/12/2025   14.9   NaN
1504  29/12/2025   14.9   NaN
1505  30/12/2025   14.9   NaN
1506  31/12/2025   14.9   NaN

In [19]:
df_merge = pd.merge(df_merge, df_pib, on='data', how='left')

In [20]:
df_merge.tail()

            data  selic  ipca  pib_brasil
1502  24/12/2025   14.9   NaN         0.4
1503  26/12/2025   14.9   NaN         0.4
1504  29/12/2025   14.9   NaN         0.4
1505  30/12/2025   14.9   NaN         0.4
1506  31/12/2025   14.9   NaN         0.4

In [21]:
df_merge.count()

data          1507
selic         1507
ipca          1485
pib_brasil    1507
dtype: int64

In [22]:
df_merge = pd.merge(df_merge, df_pib_agro, on='data', how='left')

In [23]:
df_merge.tail()

            data  selic  ipca  pib_brasil  pib_agro
1502  24/12/2025   14.9   NaN         0.4      -2.5
1503  26/12/2025   14.9   NaN         0.4      -2.5
1504  29/12/2025   14.9   NaN         0.4      -2.5
1505  30/12/2025   14.9   NaN         0.4      -2.5
1506  31/12/2025   14.9   NaN         0.4      -2.5

### Gerando o dataframe final para as variáveis Macroeconômicas

In [24]:
df_macro = pd.merge(df_merge, df_cme, on='data', how='left')

In [25]:
df_macro.tail()

            data  selic  ipca  pib_brasil  pib_agro     cme
1502  24/12/2025   14.9   NaN         0.4      -2.5  276.38
1503  26/12/2025   14.9   NaN         0.4      -2.5  276.73
1504  29/12/2025   14.9   NaN         0.4      -2.5  278.42
1505  30/12/2025   14.9   NaN         0.4      -2.5  275.83
1506  31/12/2025   14.9   NaN         0.4      -2.5  273.08

In [26]:
df_macro.shape

(1507, 6)

In [27]:
df_macro.isna().sum().sum()

np.int64(62)

## 2. Variáveis de Mercado

- Preço Boi Gordo

In [28]:
df_boi_gordo_negociado = pd.read_csv('Mercado/boi_gordo_negociado.csv', sep=',')

In [29]:
df_boi_gordo_negociado.tail()

            data  boi_real  boi_dolar
1491  22/12/2025    317.85      56.94
1492  23/12/2025    319.50      57.69
1493  26/12/2025    319.50      57.69
1494  29/12/2025    318.00      57.00
1495  30/12/2025    319.20      58.16

In [30]:
df_boi_gordo_negociado.count()

data         1496
boi_real     1496
boi_dolar    1496
dtype: int64

- Contrato Boi Gordo Futuro

In [31]:
df_boi_gordo_futuro = pd.read_csv('Mercado/boi_gordo_futuro.csv', sep=',')

In [32]:
df_boi_gordo_futuro.tail()

            data  boi_futuro
1509  24/12/2025      228.70
1510  26/12/2025      229.82
1511  29/12/2025      228.90
1512  30/12/2025      231.18
1513  31/12/2025      232.00

In [33]:
df_boi_gordo_futuro.count()

data          1514
boi_futuro    1514
dtype: int64

In [34]:
df_merge_mercado = pd.merge(df_boi_gordo_futuro, df_boi_gordo_negociado, on='data', how='left')

In [35]:
df_merge_mercado.tail()

            data  boi_futuro  boi_real  boi_dolar
1509  24/12/2025      228.70       NaN        NaN
1510  26/12/2025      229.82     319.5      57.69
1511  29/12/2025      228.90     318.0      57.00
1512  30/12/2025      231.18     319.2      58.16
1513  31/12/2025      232.00       NaN        NaN

In [36]:
df_merge_mercado.count()

data          1514
boi_futuro    1514
boi_real      1459
boi_dolar     1459
dtype: int64

- Soja

In [37]:
df_soja_negociado = pd.read_csv('Mercado/soja_negociado.csv', sep=',')

In [38]:
df_soja_negociado.tail()

            data  soja_real  soja_dolar
1492  22/12/2025     136.16       24.39
1493  23/12/2025     136.20       24.59
1494  26/12/2025     136.23       24.57
1495  29/12/2025     136.21       24.41
1496  30/12/2025     135.60       24.71

- Contrato Soja Futuro

In [39]:
df_soja_negociado.count()

data          1497
soja_real     1497
soja_dolar    1497
dtype: int64

In [40]:
df_merge_mercado = pd.merge(df_merge_mercado, df_soja_negociado, on='data', how='left')

In [41]:
df_merge_mercado.tail()

            data  boi_futuro  boi_real  boi_dolar  soja_real  soja_dolar
1509  24/12/2025      228.70       NaN        NaN        NaN         NaN
1510  26/12/2025      229.82     319.5      57.69     136.23       24.57
1511  29/12/2025      228.90     318.0      57.00     136.21       24.41
1512  30/12/2025      231.18     319.2      58.16     135.60       24.71
1513  31/12/2025      232.00       NaN        NaN        NaN         NaN

In [42]:
df_soja_futuro = pd.read_csv('Mercado/soja_futuro.csv', sep=',')

In [43]:
df_soja_futuro.tail()

            data  soja_futuro
1533  22/12/2025     232198.0
1534  23/12/2025     231812.0
1535  26/12/2025     233410.0
1536  29/12/2025     231371.0
1537  30/12/2025     234182.0

In [44]:
df_soja_futuro.count()

data           1538
soja_futuro    1538
dtype: int64

In [45]:
df_merge_mercado = pd.merge(df_merge_mercado, df_soja_futuro, on='data', how='left')

In [46]:
df_merge_mercado.tail()

,data,boi_futuro,boi_real,boi_dolar,soja_real,soja_dolar,soja_futuro
1509,24/12/2025,228.70,NaN,NaN,NaN,NaN,NaN
1510,26/12/2025,229.82,319.5,57.69,136.23,24.57,233410.0
1511,29/12/2025,228.90,318.0,57.00,136.21,24.41,231371.0
1512,30/12/2025,231.18,319.2,58.16,135.60,24.71,234182.0
1513,31/12/2025,232.00,NaN,NaN,NaN,NaN,NaN

In [47]:
df_merge_mercado.count()

data           1514
boi_futuro     1514
boi_real       1459
boi_dolar      1459
soja_real      1460
soja_dolar     1460
soja_futuro    1510
dtype: int64

- Milho

In [48]:
df_milho_futuro = pd.read_csv('Mercado/milho_futuro.csv', sep=',')

In [49]:
df_milho_futuro.tail()

            data  milho_futuro
1489  22/12/2025         70.99
1490  23/12/2025         70.81
1491  26/12/2025         70.08
1492  29/12/2025         70.28
1493  30/12/2025         70.25

In [50]:
df_milho_futuro.count()

data            1494
milho_futuro    1494
dtype: int64

In [51]:
df_merge_mercado = pd.merge(df_merge_mercado, df_milho_futuro, on='data', how='left')

In [52]:
df_merge_mercado.tail()

,data,boi_futuro,boi_real,boi_dolar,soja_real,soja_dolar,soja_futuro,milho_futuro
1509,24/12/2025,228.70,NaN,NaN,NaN,NaN,NaN,NaN
1510,26/12/2025,229.82,319.5,57.69,136.23,24.57,233410.0,70.08
1511,29/12/2025,228.90,318.0,57.00,136.21,24.41,231371.0,70.28
1512,30/12/2025,231.18,319.2,58.16,135.60,24.71,234182.0,70.25
1513,31/12/2025,232.00,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
df_milho_negociado = pd.read_csv('Mercado/milho_negociado.csv', sep=',')

In [54]:
df_milho_negociado.tail()

            data  milho_real  milho_dolar
1492  22/12/2025       69.47        12.45
1493  23/12/2025       69.50        12.55
1494  26/12/2025       69.48        12.53
1495  29/12/2025       69.46        12.45
1496  30/12/2025       69.50        12.66

In [55]:
df_milho_negociado.count()

data           1497
milho_real     1497
milho_dolar    1497
dtype: int64

In [56]:
df_merge_mercado = pd.merge(df_merge_mercado, df_milho_negociado, on='data', how='left')

In [57]:
df_merge_mercado.tail()

,data,boi_futuro,boi_real,boi_dolar,soja_real,soja_dolar,soja_futuro,milho_futuro,milho_real,milho_dolar
1509,24/12/2025,228.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1510,26/12/2025,229.82,319.5,57.69,136.23,24.57,233410.0,70.08,69.48,12.53
1511,29/12/2025,228.90,318.0,57.00,136.21,24.41,231371.0,70.28,69.46,12.45
1512,30/12/2025,231.18,319.2,58.16,135.60,24.71,234182.0,70.25,69.50,12.66
1513,31/12/2025,232.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
df_merge_mercado.count()

data            1514
boi_futuro      1514
boi_real        1459
boi_dolar       1459
soja_real       1460
soja_dolar      1460
soja_futuro     1510
milho_futuro    1457
milho_real      1460
milho_dolar     1460
dtype: int64

In [59]:
df_dolar = pd.read_csv('Mercado/dolar.csv', sep=',')

In [60]:
df_dolar.tail()

            data  dolar
1557  22/12/2025  5.582
1558  23/12/2025  5.538
1559  26/12/2025  5.544
1560  29/12/2025  5.579
1561  30/12/2025  5.488

In [61]:
df_dolar.count()

data     1562
dolar    1562
dtype: int64

In [62]:
df_merge_mercado = pd.merge(df_merge_mercado, df_dolar, on='data', how='left')

In [63]:
df_merge_mercado.tail()

,data,boi_futuro,boi_real,boi_dolar,soja_real,soja_dolar,soja_futuro,milho_futuro,milho_real,milho_dolar,dolar
1509,24/12/2025,228.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1510,26/12/2025,229.82,319.5,57.69,136.23,24.57,233410.0,70.08,69.48,12.53,5.544
1511,29/12/2025,228.90,318.0,57.00,136.21,24.41,231371.0,70.28,69.46,12.45,5.579
1512,30/12/2025,231.18,319.2,58.16,135.60,24.71,234182.0,70.25,69.50,12.66,5.488
1513,31/12/2025,232.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
df_tarifa_china = pd.read_csv('Mercado/tarifa_China.csv', sep=',')

In [65]:
df_tarifa_china.tail()

            data  Taxa_china
2187  27/12/2025        0.12
2188  28/12/2025        0.12
2189  29/12/2025        0.12
2190  30/12/2025        0.12
2191  31/12/2025        0.12

In [66]:
df_mercado = pd.merge(df_tarifa_china, df_merge_mercado, on='data', how='left')

In [67]:
df_tarifa_UE = pd.read_csv('Mercado/tarifa_UE.csv', sep=',')

In [68]:
df_tarifa_UE.tail()

            data  Taxa_EU
2187  27/12/2025     0.42
2188  28/12/2025     0.42
2189  29/12/2025     0.42
2190  30/12/2025     0.42
2191  31/12/2025     0.42

In [69]:
df_mercado = pd.merge(df_tarifa_UE, df_mercado, on='data', how='left')

In [70]:
df_tarifa_EUA = pd.read_csv('Mercado/tarifa_EUA.csv', sep=',')

In [71]:
df_tarifa_EUA.tail()

            data  Taxa_EUA
2187  27/12/2025      0.26
2188  28/12/2025      0.26
2189  29/12/2025      0.26
2190  30/12/2025      0.26
2191  31/12/2025      0.26

### Gerando o dataframe final para as variáveis de mercado

In [72]:
df_mercado = pd.merge(df_tarifa_EUA, df_mercado, on='data', how='left')

In [73]:
df_mercado.tail()

,data,Taxa_EUA,Taxa_EU,Taxa_china,boi_futuro,boi_real,boi_dolar,soja_real,soja_dolar,soja_futuro,milho_futuro,milho_real,milho_dolar,dolar
2187,27/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2188,28/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2189,29/12/2025,0.26,0.42,0.12,228.90,318.0,57.00,136.21,24.41,231371.0,70.28,69.46,12.45,5.579
2190,30/12/2025,0.26,0.42,0.12,231.18,319.2,58.16,135.60,24.71,234182.0,70.25,69.50,12.66,5.488
2191,31/12/2025,0.26,0.42,0.12,232.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
df_mercado.shape

(2192, 14)

In [75]:
df_mercado.isna().sum().sum()

np.int64(7170)

## 3. Variáveis Climáticas

- Precipitação por região produtora

In [76]:
df_precip_area = pd.read_csv('Climaticas/INMET.csv', sep=',')

In [77]:
df_precip_area.tail()

            data  precip_total_mm
1966  27/12/2025              0.0
1967  28/12/2025              0.0
1968  29/12/2025              0.0
1969  30/12/2025              0.0
1970  31/12/2025             10.8

In [78]:
df_precip_area.count()

data               1971
precip_total_mm    1971
dtype: int64

- Temperatura Média

In [79]:
df_temp_regiao = pd.read_csv('Climaticas/temp.csv')

In [80]:
df_temp_regiao.tail()

            data  TEMPERATURA
2187  27/12/2025        29.90
2188  28/12/2025        30.06
2189  29/12/2025        28.14
2190  30/12/2025        27.66
2191  31/12/2025        26.90

In [81]:
df_temp_regiao.count()

data           2192
TEMPERATURA    2158
dtype: int64

- Índices de seca (Palmer Drought Severity Index)

Valor do PDSI	Interpretação
≥ +4,0	        Muito úmido
+3,0 a +3,9	    Moderadamente úmido
+2,0 a +2,9	    Levemente úmido
+1,0 a +1,9	    Condições normais (úmidas)
0,0 a +0,9	    Normal
-0,9 a 0,0	    Normal
-1,0 a -1,9	    Levemente seco
-2,0 a -2,9	    Moderadamente seco
-3,0 a -3,9	    Severamente seco
≤ -4,0	        Extremamente seco

In [82]:
df_scpdsi = pd.read_csv('Climaticas/scpdsi.csv')

In [83]:
df_scpdsi.count()

data      2192
scpdsi    2192
dtype: int64

In [84]:
df_scpdsi.tail()

            data  scpdsi
2187  27/12/2025    -0.0
2188  28/12/2025    -0.0
2189  29/12/2025    -0.0
2190  30/12/2025    -0.0
2191  31/12/2025    -0.0

- El niño

In [85]:
df_el_nino = pd.read_csv('Climaticas/el_nino.csv')

In [86]:
df_el_nino.count()

data       2209
el nino    2209
dtype: int64

In [87]:
df_el_nino.tail()

            data      el nino
2204  27/12/2025  INEXISTENTE
2205  28/12/2025  INEXISTENTE
2206  29/12/2025  INEXISTENTE
2207  30/12/2025  INEXISTENTE
2208  31/12/2025  INEXISTENTE

In [88]:
df_climaticas = pd.merge(df_scpdsi, df_el_nino, on='data', how='left')

In [89]:
df_climaticas.tail()

            data  scpdsi      el nino
2204  27/12/2025    -0.0  INEXISTENTE
2205  28/12/2025    -0.0  INEXISTENTE
2206  29/12/2025    -0.0  INEXISTENTE
2207  30/12/2025    -0.0  INEXISTENTE
2208  31/12/2025    -0.0  INEXISTENTE

In [90]:
df_climaticas.count()

data       2209
scpdsi     2209
el nino    2209
dtype: int64

In [91]:
df_climaticas = pd.merge(df_climaticas, df_precip_area, on='data', how='left')

In [92]:
df_climaticas = pd.merge(df_climaticas, df_temp_regiao, on='data', how='left')

In [93]:
df_climaticas.tail()

            data  scpdsi      el nino  precip_total_mm  TEMPERATURA
2204  27/12/2025    -0.0  INEXISTENTE              0.0        29.90
2205  28/12/2025    -0.0  INEXISTENTE              0.0        30.06
2206  29/12/2025    -0.0  INEXISTENTE              0.0        28.14
2207  30/12/2025    -0.0  INEXISTENTE              0.0        27.66
2208  31/12/2025    -0.0  INEXISTENTE             10.8        26.90

In [94]:
df_climaticas.count()

data               2209
scpdsi             2209
el nino            2209
precip_total_mm    1988
TEMPERATURA        2175
dtype: int64

## 4. Variáveis Sazonais

- Ciclo Reprodutivo do gado

In [95]:
df_ciclo_rep_gado = pd.read_csv('Sazonais/rep_gado.csv')

In [96]:
df_ciclo_rep_gado.tail()

            data          ciclo
2187  27/12/2025  ESTACAO_MONTA
2188  28/12/2025  ESTACAO_MONTA
2189  29/12/2025  ESTACAO_MONTA
2190  30/12/2025  ESTACAO_MONTA
2191  31/12/2025  ESTACAO_MONTA

In [97]:
df_ciclo_rep_gado.count()

data     2192
ciclo    2192
dtype: int64

- Safra e Entresafra

In [98]:
df_safra_entresafra = pd.read_csv('Sazonais/safra_entresafra.csv')

In [99]:
df_safra_entresafra.tail()

            data       aspecto
2187  27/12/2025  PLANEJAMENTO
2188  28/12/2025  PLANEJAMENTO
2189  29/12/2025  PLANEJAMENTO
2190  30/12/2025  PLANEJAMENTO
2191  31/12/2025  PLANEJAMENTO

In [100]:
df_safra_entresafra.count()

data       2192
aspecto    2192
dtype: int64

- Festas e datas comemorativas

In [101]:
df_festas = pd.read_csv('Sazonais/festas_2020_2025.csv')

In [102]:
df_festas.tail()

,data,ano_novo_flag,carnaval_core_flag,carnaval_window_flag,pascoa_flag,pascoa_window_flag,dias_maes_flag,dias_maes_weekend_flag,festas_juninas_flag,santo_antonio_flag,...,dias_pais_weekend_flag,independencia_flag,independencia_window_flag,dia_criancas_flag,finados_flag,finados_weekend_flag,natal_flag,natal_window_flag,fim_ano_window_flag,sazonal_carne_weight
2187,27/12/2025,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
2188,28/12/2025,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
2189,29/12/2025,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
2190,30/12/2025,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1.5
2191,31/12/2025,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1.5

In [103]:
df_festas.count()

data                         2192
ano_novo_flag                2192
carnaval_core_flag           2192
carnaval_window_flag         2192
pascoa_flag                  2192
pascoa_window_flag           2192
dias_maes_flag               2192
dias_maes_weekend_flag       2192
festas_juninas_flag          2192
santo_antonio_flag           2192
sao_joao_flag                2192
sao_pedro_flag               2192
ferias_midyear_flag          2192
ferias_verao_flag            2192
dias_pais_flag               2192
dias_pais_weekend_flag       2192
independencia_flag           2192
independencia_window_flag    2192
dia_criancas_flag            2192
finados_flag                 2192
finados_weekend_flag         2192
natal_flag                   2192
natal_window_flag            2192
fim_ano_window_flag          2192
sazonal_carne_weight         2192
dtype: int64

In [104]:
df_sazonais = pd.merge(df_ciclo_rep_gado, df_safra_entresafra, on='data', how='left')

In [105]:
df_sazonais.tail()

            data          ciclo       aspecto
2187  27/12/2025  ESTACAO_MONTA  PLANEJAMENTO
2188  28/12/2025  ESTACAO_MONTA  PLANEJAMENTO
2189  29/12/2025  ESTACAO_MONTA  PLANEJAMENTO
2190  30/12/2025  ESTACAO_MONTA  PLANEJAMENTO
2191  31/12/2025  ESTACAO_MONTA  PLANEJAMENTO

In [106]:
df_sazonais = pd.merge(df_sazonais, df_festas, on='data', how='left')

In [107]:
df_sazonais.tail()

,data,ciclo,aspecto,ano_novo_flag,carnaval_core_flag,carnaval_window_flag,pascoa_flag,pascoa_window_flag,dias_maes_flag,dias_maes_weekend_flag,...,dias_pais_weekend_flag,independencia_flag,independencia_window_flag,dia_criancas_flag,finados_flag,finados_weekend_flag,natal_flag,natal_window_flag,fim_ano_window_flag,sazonal_carne_weight
2187,27/12/2025,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
2188,28/12/2025,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
2189,29/12/2025,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
2190,30/12/2025,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1.5
2191,31/12/2025,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1.5

In [108]:
df_sazonais.count()

data                         2192
ciclo                        2192
aspecto                      2192
ano_novo_flag                2192
carnaval_core_flag           2192
carnaval_window_flag         2192
pascoa_flag                  2192
pascoa_window_flag           2192
dias_maes_flag               2192
dias_maes_weekend_flag       2192
festas_juninas_flag          2192
santo_antonio_flag           2192
sao_joao_flag                2192
sao_pedro_flag               2192
ferias_midyear_flag          2192
ferias_verao_flag            2192
dias_pais_flag               2192
dias_pais_weekend_flag       2192
independencia_flag           2192
independencia_window_flag    2192
dia_criancas_flag            2192
finados_flag                 2192
finados_weekend_flag         2192
natal_flag                   2192
natal_window_flag            2192
fim_ano_window_flag          2192
sazonal_carne_weight         2192
dtype: int64

## 5. Variáveis Exógenas

- COVID-19

In [109]:
df_covid = pd.read_csv('Exogenas/covid_2020_2025.csv')

In [110]:
df_covid.tail()

            data  CovidPeriodFlag
2187  27/12/2025                0
2188  28/12/2025                0
2189  29/12/2025                0
2190  30/12/2025                0
2191  31/12/2025                0

In [111]:
df_covid.count()

data               2192
CovidPeriodFlag    2192
dtype: int64

## Criando o dataframe Final

In [112]:
max(df_mercado.count())

2192

In [113]:
df_mercado.tail()

,data,Taxa_EUA,Taxa_EU,Taxa_china,boi_futuro,boi_real,boi_dolar,soja_real,soja_dolar,soja_futuro,milho_futuro,milho_real,milho_dolar,dolar
2187,27/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2188,28/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2189,29/12/2025,0.26,0.42,0.12,228.90,318.0,57.00,136.21,24.41,231371.0,70.28,69.46,12.45,5.579
2190,30/12/2025,0.26,0.42,0.12,231.18,319.2,58.16,135.60,24.71,234182.0,70.25,69.50,12.66,5.488
2191,31/12/2025,0.26,0.42,0.12,232.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [114]:
max(df_macro.count())

1507

In [115]:
df_macro.tail()

            data  selic  ipca  pib_brasil  pib_agro     cme
1502  24/12/2025   14.9   NaN         0.4      -2.5  276.38
1503  26/12/2025   14.9   NaN         0.4      -2.5  276.73
1504  29/12/2025   14.9   NaN         0.4      -2.5  278.42
1505  30/12/2025   14.9   NaN         0.4      -2.5  275.83
1506  31/12/2025   14.9   NaN         0.4      -2.5  273.08

In [116]:
max(df_climaticas.count())

2209

In [117]:
df_climaticas.tail()

            data  scpdsi      el nino  precip_total_mm  TEMPERATURA
2204  27/12/2025    -0.0  INEXISTENTE              0.0        29.90
2205  28/12/2025    -0.0  INEXISTENTE              0.0        30.06
2206  29/12/2025    -0.0  INEXISTENTE              0.0        28.14
2207  30/12/2025    -0.0  INEXISTENTE              0.0        27.66
2208  31/12/2025    -0.0  INEXISTENTE             10.8        26.90

In [118]:
max(df_sazonais.count())

2192

In [119]:
df_sazonais.tail()

,data,ciclo,aspecto,ano_novo_flag,carnaval_core_flag,carnaval_window_flag,pascoa_flag,pascoa_window_flag,dias_maes_flag,dias_maes_weekend_flag,...,dias_pais_weekend_flag,independencia_flag,independencia_window_flag,dia_criancas_flag,finados_flag,finados_weekend_flag,natal_flag,natal_window_flag,fim_ano_window_flag,sazonal_carne_weight
2187,27/12/2025,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
2188,28/12/2025,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
2189,29/12/2025,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
2190,30/12/2025,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1.5
2191,31/12/2025,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1.5

In [120]:
max(df_covid.count())

2192

In [121]:
df_covid.tail()

            data  CovidPeriodFlag
2187  27/12/2025                0
2188  28/12/2025                0
2189  29/12/2025                0
2190  30/12/2025                0
2191  31/12/2025                0

In [122]:
df_final = pd.merge(df_covid, df_sazonais, on='data', how='left')

In [123]:
df_final.tail()

,data,CovidPeriodFlag,ciclo,aspecto,ano_novo_flag,carnaval_core_flag,carnaval_window_flag,pascoa_flag,pascoa_window_flag,dias_maes_flag,...,dias_pais_weekend_flag,independencia_flag,independencia_window_flag,dia_criancas_flag,finados_flag,finados_weekend_flag,natal_flag,natal_window_flag,fim_ano_window_flag,sazonal_carne_weight
2187,27/12/2025,0,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
2188,28/12/2025,0,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
2189,29/12/2025,0,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
2190,30/12/2025,0,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1.5
2191,31/12/2025,0,ESTACAO_MONTA,PLANEJAMENTO,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1.5

In [124]:
df_final = pd.merge(df_final, df_climaticas, on='data', how='left')

In [125]:
df_final = pd.merge(df_final, df_macro, on='data', how='left')

In [126]:
df_agro_boi = pd.merge(df_mercado, df_final, on='data', how='left')

In [127]:
df_agro_boi.tail()

,data,Taxa_EUA,Taxa_EU,Taxa_china,boi_futuro,boi_real,boi_dolar,soja_real,soja_dolar,soja_futuro,...,sazonal_carne_weight,scpdsi,el nino,precip_total_mm,TEMPERATURA,selic,ipca,pib_brasil,pib_agro,cme
2204,27/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.0,INEXISTENTE,0.0,29.90,NaN,NaN,NaN,NaN,NaN
2205,28/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.0,INEXISTENTE,0.0,30.06,NaN,NaN,NaN,NaN,NaN
2206,29/12/2025,0.26,0.42,0.12,228.90,318.0,57.00,136.21,24.41,231371.0,...,0.0,-0.0,INEXISTENTE,0.0,28.14,14.9,NaN,0.4,-2.5,278.42
2207,30/12/2025,0.26,0.42,0.12,231.18,319.2,58.16,135.60,24.71,234182.0,...,1.5,-0.0,INEXISTENTE,0.0,27.66,14.9,NaN,0.4,-2.5,275.83
2208,31/12/2025,0.26,0.42,0.12,232.00,NaN,NaN,NaN,NaN,NaN,...,1.5,-0.0,INEXISTENTE,10.8,26.90,14.9,NaN,0.4,-2.5,273.08

In [128]:
df_agro_boi.shape

(2209, 50)

In [129]:
s = df_agro_boi.shape[0]  * df_agro_boi.shape[1]

In [130]:
s

110450

In [135]:
df_agro_boi.dtypes

data                          object
Taxa_EUA                     float64
Taxa_EU                      float64
Taxa_china                   float64
boi_futuro                   float64
boi_real                     float64
boi_dolar                    float64
soja_real                    float64
soja_dolar                   float64
soja_futuro                  float64
milho_futuro                 float64
milho_real                   float64
milho_dolar                  float64
dolar                        float64
CovidPeriodFlag                int64
ciclo                         object
aspecto                       object
ano_novo_flag                  int64
carnaval_core_flag             int64
carnaval_window_flag           int64
pascoa_flag                    int64
pascoa_window_flag             int64
dias_maes_flag                 int64
dias_maes_weekend_flag         int64
festas_juninas_flag            int64
santo_antonio_flag             int64
sao_joao_flag                  int64
sao_pedro_flag                 int64
ferias_midyear_flag            int64
ferias_verao_flag              int64
dias_pais_flag                 int64
dias_pais_weekend_flag         int64
independencia_flag             int64
independencia_window_flag      int64
dia_criancas_flag              int64
finados_flag                   int64
finados_weekend_flag           int64
natal_flag                     int64
natal_window_flag              int64
fim_ano_window_flag            int64
sazonal_carne_weight         float64
scpdsi                       float64
el nino                       object
precip_total_mm              float64
TEMPERATURA                  float64
selic                        float64
ipca                         float64
pib_brasil                   float64
pib_agro                     float64
cme                          float64
dtype: object

In [ ]:
df_agro_boi.drop(columns=[])

In [132]:
df_agro_boi.to_csv("dados_agro.csv", index=False)

In [2]:
df = pd.read_csv("dados_agro.csv", index_col=0)
df.tail()

,Taxa_EUA,Taxa_EU,Taxa_china,boi_futuro,boi_real,boi_dolar,soja_real,soja_dolar,soja_futuro,milho_futuro,...,sazonal_carne_weight,scpdsi,el nino,precip_total_mm,TEMPERATURA,selic,ipca,pib_brasil,pib_agro,cme
data,,,,,,,,,,,,,,,,,,,,,
27/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.0,INEXISTENTE,0.0,29.90,NaN,NaN,NaN,NaN,NaN
28/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.0,INEXISTENTE,0.0,30.06,NaN,NaN,NaN,NaN,NaN
29/12/2025,0.26,0.42,0.12,228.90,318.0,57.00,136.21,24.41,231371.0,70.28,...,0.0,-0.0,INEXISTENTE,0.0,28.14,14.9,NaN,0.4,-2.5,278.42
30/12/2025,0.26,0.42,0.12,231.18,319.2,58.16,135.60,24.71,234182.0,70.25,...,1.5,-0.0,INEXISTENTE,0.0,27.66,14.9,NaN,0.4,-2.5,275.83
31/12/2025,0.26,0.42,0.12,232.00,NaN,NaN,NaN,NaN,NaN,NaN,...,1.5,-0.0,INEXISTENTE,10.8,26.90,14.9,NaN,0.4,-2.5,273.08

In [6]:
df.rename(columns={"boi_real":"boi_negociado"}, inplace=True)
df.tail()

,Taxa_EUA,Taxa_EU,Taxa_china,boi_futuro,boi_negociado,boi_dolar,soja_real,soja_dolar,soja_futuro,milho_futuro,...,sazonal_carne_weight,scpdsi,el nino,precip_total_mm,TEMPERATURA,selic,ipca,pib_brasil,pib_agro,cme
data,,,,,,,,,,,,,,,,,,,,,
27/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.0,INEXISTENTE,0.0,29.90,NaN,NaN,NaN,NaN,NaN
28/12/2025,0.26,0.42,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.0,INEXISTENTE,0.0,30.06,NaN,NaN,NaN,NaN,NaN
29/12/2025,0.26,0.42,0.12,228.90,318.0,57.00,136.21,24.41,231371.0,70.28,...,0.0,-0.0,INEXISTENTE,0.0,28.14,14.9,NaN,0.4,-2.5,278.42
30/12/2025,0.26,0.42,0.12,231.18,319.2,58.16,135.60,24.71,234182.0,70.25,...,1.5,-0.0,INEXISTENTE,0.0,27.66,14.9,NaN,0.4,-2.5,275.83
31/12/2025,0.26,0.42,0.12,232.00,NaN,NaN,NaN,NaN,NaN,NaN,...,1.5,-0.0,INEXISTENTE,10.8,26.90,14.9,NaN,0.4,-2.5,273.08

In [7]:
df.to_csv("dados_agro_atualizado.csv", index=False)

In [8]:
new_df = pd.read_csv("dados_agro_atualizado.csv", index_col=0)

In [9]:
new_df[["ciclo","aspecto", "el nino"]].tail()

                  ciclo       aspecto      el nino
Taxa_EUA
0.26      ESTACAO_MONTA  PLANEJAMENTO  INEXISTENTE
0.26      ESTACAO_MONTA  PLANEJAMENTO  INEXISTENTE
0.26      ESTACAO_MONTA  PLANEJAMENTO  INEXISTENTE
0.26      ESTACAO_MONTA  PLANEJAMENTO  INEXISTENTE
0.26      ESTACAO_MONTA  PLANEJAMENTO  INEXISTENTE